### ISSUE TITLE
technic_worldgen breaks energy values on dev branch

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#10]
**Describe the bug**
Enabling technic_worldgen from [mt-mods](https://github.com/mt-mods/technic) causes energy values for most ingot types to not be set.

**Expected behavior**
iron, gold, tin, etc. ingots have energy values

**Game (e.g. Minetest Game)**
Minetest Game 5.8.0

**Additional context**
exchangeclone is at commit d5c153e45faeb00d827d814562cc511d6ea12c81
technic is at commit https://github.com/mt-mods/technic/commit/f1b99282e889e9a483c76af95ee3370b6d2b2d04

reproduction steps:
* install technic from https://github.com/mt-mods/technic at commit f1b99282e889e9a483c76af95ee3370b6d2b2d04
* create new world based on minetest game 5.8.0
* enable exchangeclone dev modpack
* enable technic_worldgen from technic_mc_compat (editing world.mt might be easiest)
* run game
* look up ingots, observe that iron ingot has no energy value.

**Comment by programmerjake** [comment]
oops, I forgot to enable exchange clone...I did run into this problem with more mods enabled tho, idk which mods are causing it yet, I'll check.

**Comment by programmerjake** [comment]
turns out it was technic from https://github.com/mt-mods/technic/pull/328, updated the top comment and title to match

**Comment by programmerjake** [comment]
turns out it's not the mineclone compatibility PR, it's just the latest changes in technic master, available from contentdb at https://content.minetest.net/packages/mt-mods/technic_plus_beta/

**Comment by ThePython10110** [comment]
Interesting. I've been testing with Technic, but not the beta version. I may not be able to test stuff today (with it being Christmas and stuff), but I'll probably check that out tomorrow.

**Comment by programmerjake** [comment]
do note that there's actually several different versions of technic: the one at https://github.com/mt-mods/technic (called Technic Plus/Technic Plus Beta in contentdb, the one I'm having issues with) and the one at https://github.com/minetest-mods/technic (called Technic in contentdb)

**Comment by ThePython10110** [comment]
I figured it out... apparently I was handling aliases badly. Basically, if there were recipes where the output was an alias, they would completely overwrite all the recipes of the original item. This is now fixed.
