### ISSUE TITLE
worn tools give excessive energy back

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#11]
**Describe the bug**
When converting a diamond pick back to energy, if it's slightly worn it can give a huge amount of energy back (20,135,936 when I tested it), which is waay more than a new diamond pick costs (24,580).

**Expected behavior**
worn diamond picks to not give more energy back than they originally cost.

**Game (e.g. Minetest Game)**
Minetest Game 5.8.0

**Comment by ThePython10110** [comment]
Fixed.
