### ISSUE TITLE
[Feature Request] put tome of everything behind a privilege and/or server flag 

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#12]
**Is your feature request related to a problem? Please describe.**
I find that when playing games with ExchangeClone, once you get enough energy to buy a Tome of Everything, you have near-creative mode which effectively removes all need to explore or craft anything to get new materials you haven't seen before, removing a major aspect of what makes the game interesting.

**Describe the solution you'd like**
give the option to disallow the Tome of Everything to avoid the above problem. this could be a privilege for on servers where admins could have a Tome of Everything as a less-cheating substitute for the `give` privilege, it could also be a server setting to disable it server-wide.

**Describe alternatives you've considered**
pretending it doesn't exist...

**Comment by ThePython10110** [comment]
There is now a setting to enable/disable the crafting recipe.

**Comment by programmerjake** [comment]
> There is now a setting to enable/disable the crafting recipe.

Thanks!
