### ISSUE TITLE
[Bug] incorrect escaping in formspecs

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#17]
**Describe the bug**
typing a `;` in the transmutation table search box causes the search box to disappear and the client to give the error "invalid field element..."

**Expected behavior**
searching for semicolons to work

**Game (e.g. Minetest Game)**
Minetest Game

this looks like you forgot a `minetest.formspec_escape` call

**Comment by ThePython10110** [comment]
That was the issue, thanks.
