### ISSUE TITLE
[Bug] Duplicating Red Matter Swords

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#18]
**Describe the bug**
Create a new world in creative mode with Minetest Game, anvil, mobs_water, and toolranks.
Give yourself a red matter sword.
Spawn a turtle using a turtle spawn egg.
punch the turtle with the sword -- observe that the sword is now damaged -- this is a bug.
place an anvil.
right click the anvil with the damaged sword.
right click the anvil with nothing in your hand.
observe that you now have two red matter swords -- this is a more serious bug.

**Expected behavior**
red matter swords can't be damaged. damaged red matter swords can't be duplicated.

**Game (e.g. Minetest Game)**
Minetest Game.

**Comment by ThePython10110** [comment]
I fixed the duplication, but the damage is a problem with the Mobs Redo mod. I reported this, so hopefully it will get fixed.

**Comment by programmerjake** [comment]
Thanks!
