### ISSUE TITLE
[Bug] Gem of Eternal Density doesn't respect actual hotbar size

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#19]
**Describe the bug**
Using dreambuilder_hotbar and other similar mods, you can set the hotbar to any size you please. Gem of Eternal Density has hardcoded values instead of using `player:hud_get_hotbar_itemcount()`

**Expected behavior**
use `player:hud_get_hotbar_itemcount()` to get the correct hotbar size.

**Game (e.g. Minetest Game)**
Minetest Game

**Comment by ThePython10110** [comment]
Fixed.
