### ISSUE TITLE
Crashes in minclonia

### ISSUE THREAD

**Issue by Ranko-Saotome** [ThePython10110/ExchangeClone#2]
ModError: Failed to load and run script from /home/owner/Applications/minetest-5.7.0-stable/bin/../mods/exchangeclone/init.lua:
...ble/bin/../games/mineclonia/mods/ITEMS/mcl_armor/api.lua:121: attempt to index field 'descriptions' (a nil value)
stack traceback:
	...ble/bin/../games/mineclonia/mods/ITEMS/mcl_armor/api.lua:121: in function 'register_set'
	...inetest-5.7.0-stable/bin/../mods/exchangeclone/armor.lua:91: in main chunk
	[C]: in function 'dofile'
	...minetest-5.7.0-stable/bin/../mods/exchangeclone/init.lua:21: in main chunk
Check debug.txt for details.

**Comment by ThePython10110** [comment]
Try it with MineClone2. If *that* works, then I'll know that it's just a problem with Mineclonia.

**Comment by Ranko-Saotome** [comment]
it works in mineclone2 as of the latest git master since minecclonia was a fork of mineclone2  assumed it would work.

**Comment by ThePython10110** [comment]
Interesting. I've never actually played Mineclonia or looked at its code, but apparently it registers armor sets differently. I'll look at it and see if I can fix it.

**Comment by ThePython10110** [comment]
I added Mineclonia support, but ContentDB isn't currently letting me release it at the moment ("unknown server error"). I'll release it as soon as possible.
