### ISSUE TITLE
[Feature Request] Make Gem of Eternal Density cause player to learn the transmuted items

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#20]
**Is your feature request related to a problem? Please describe.**
When using the Gem of Eternal Density, I sometimes mine things I haven't learned yet, I want to be able to learn them without them being converted to energy before I have a chance.

**Describe the solution you'd like**
The Gem of Eternal Density automatically causes the player to learn all items it converts.

**Describe alternatives you've considered**
* Have the Gem of Eternal Density not convert items until you've learned them.
* Don't use the Gem of Eternal Density

**Comment by ThePython10110** [comment]
ProjectE doesn't work this way, so I'm not going to do it. You could always just deactivate it and manually learn and condense things when your inventory gets full, although I see how that would be annoying.

**Comment by programmerjake** [comment]
well, if it's annoying, it's worth fixing imo. if ProjectE doesn't do it I'd consider that a bug/missing-feature in ProjectE. do remember that ProjectE isn't necessarily perfect.

**Comment by ThePython10110** [comment]
Now that I think of it, ProjectE does have a whitelist/blacklist feature... I was trying to avoid overriding left click, but I guess I will.

**Comment by programmerjake** [comment]
noticed it defaults to learned items only if you don't open the formspec...nice! also, thanks for the additional mod support!

**Comment by ThePython10110** [comment]
What do you mean? It definitely defaults to blacklist for me. Maybe I should have mentioned that the filter was stored with the player, not the itemstack.

**Comment by programmerjake** [comment]
ah, i misread https://github.com/ThePython10110/ExchangeClone/blob/8682dae7540a598ee5bf556f4b8362c4079894c6/exchangeclone/gem_of_eternal_density.lua#L39
