### ISSUE TITLE
Dark Oak Logs Energy Level is Zero

### ISSUE THREAD

**Issue by Ranko-Saotome** [ThePython10110/ExchangeClone#4]
I've noticed that in Mineclonia, the dark oak logs are showing an energy level of zero. I'm unsure if this is intended behavior or a bug, so I wanted to bring it to your attention for further investigation.

**Comment by ThePython10110** [comment]
This is definitely unintentional; apparently some item groups in Mineclonia have different names. This will be fixed in the next update.

**Comment by ThePython10110** [comment]
Fixed.
