### ISSUE TITLE
Some strange debug code gets outputted by the server

### ISSUE THREAD

**Issue by Ranko-Saotome** [ThePython10110/ExchangeClone#5]
**Describe the bug**

Some strange debug code gets outputted by the server

**Expected behavior**

nothing to show up

**Game (e.g. Minetest Game)**
Which game were you playing?
 Mineclonia 0.91.0
**Screenshots**

![Screenshot from 2023-11-07 19-17-00](https://github.com/ThePython10110/ExchangeClone/assets/76974974/5c947706-db02-4258-b832-98384d24af4b)

**Additional context**
 steps to reproduce

Start a new world with exchangeclone enabled
Don't have any armor
and  Fall from a distance

**Comment by corarona** [comment]
I was discussing the bug with Ranko and found that it's in armor.lua:114, also discovered these on the way:

```
$ grep -nir minetest.log *.lua

armor.lua:114:        minetest.log(dump({damage, reason}))
energy_collector.lua:251:                    minetest.log(inv:room_for_item("main", stack))
energy_collector.lua:254:                    minetest.log("failed")
energy.lua:1867:    --minetest.log(itemstring.." "..energy_value.." "..reason)
philosophers_stone.lua:416:                    minetest.log(dump({item_type, name}))
philosophers_stone.lua:424:        minetest.log(dump({phil=phil,fuel=fuel,item_type=item_type,item_count=item_count}))
philosophers_stone.lua:455:                    minetest.log(dump({item_type, name}))
philosophers_stone.lua:463:        minetest.log(dump({phil=phil,fuel=fuel,item_type=item_type,item_count=item_count}))
swords.lua:109:				--minetest.log(dump({name=ent.name, distance=distance, damage=damage}))
```

**Comment by ThePython10110** [comment]
Fixed (I fixed it already, but apparently didn't release it correctly).

Only the armor one was actually running; all the other ones are in commented sections of code.
