### ISSUE TITLE
Mineclonia Crash

### ISSUE THREAD

**Issue by Ranko-Saotome** [ThePython10110/ExchangeClone#6]
**Describe the bug**

AsyncErr: Lua: Runtime error from mod 'mcl_potions' in callback item_OnPlace(): ...bin/../games/mineclonia/mods/ITEMS/mcl_beehives/init.lua:10: attempt to index local 'player' (a nil value)
stack traceback:
    ...bin/../games/mineclonia/mods/ITEMS/mcl_beehives/init.lua:10: in function 'old_honey_harvest'
    ...ames/minetest-5.7.0/bin/../mods/exchangeclone/shears.lua:259: in function 'on_rightclick'
    .../bin/../games/mineclonia/mods/ITEMS/mcl_potions/init.lua:60: in function <.../bin/../games/mineclonia/mods/ITEMS/mcl_potions/init.lua:52>

**Expected behavior**

not to crash

**Game (e.g. Minetest Game)**
Which game were you playing?

mineclonia 0.91.0

**Screenshots**

N/A

**Additional context**

 try to harvest honey with exchangeclone enabled

**Comment by ThePython10110** [comment]
I had to do some things when I made the Dark and Red Matter Shears. I didn't realize Mineclonia handled beehives differently. I'll fix this as soon as I can.

**Comment by ThePython10110** [comment]
Wow. That had nothing to do with Mineclonia (I think), and would have done exactly the same thing in MineClone2. I just completely failed to notice that.
