### ISSUE TITLE
add support for hopper mod

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#7]
**Is your feature request related to a problem? Please describe.**
I can't use the constructor/destructor with [hopper](https://content.minetest.net/packages/FaceDeer/hopper/)s.

**Describe the solution you'd like**
add support for the hopper mod

**Describe alternatives you've considered**
I tried using the [pipeworks](https://content.minetest.net/packages/mt-mods/pipeworks/) mod, it doesn't work either.

https://github.com/minetest-mods/hopper/blob/master/api.txt

**Comment by ThePython10110** [comment]
I'll try to add hopper/pipeworks support in the next update.

**Comment by ThePython10110** [comment]
Hoppers now work (though I'm not ready to release the update yet)

**Comment by programmerjake** [comment]
> Hoppers now work

nice! i noticed you also added pipeworks stuff in the commit. maybe close #8 if it works?

**Comment by ThePython10110** [comment]
Still working on Pipeworks, but it'll be done soon. I pretty much just commit whenever I feel like it (which isn't the best way of doing things, I'm sure, but whatever).
