### ISSUE TITLE
support for pipeworks

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#8]
**Is your feature request related to a problem? Please describe.**
I can't use the constructor/destructor with any [pipeworks](https://content.minetest.net/packages/mt-mods/pipeworks/) tubes

**Describe the solution you'd like**
add support for pipeworks

**Describe alternatives you've considered**
I tried using the [hopper](https://content.minetest.net/packages/FaceDeer/hopper/) mod, it doesn't work either.

https://github.com/mt-mods/pipeworks/wiki/api.md#tube-definition-in-node-definition

**Comment by ThePython10110** [comment]
I'll try to add hopper/pipeworks support in the next update.

**Comment by ThePython10110** [comment]
Added Pipeworks support.
